# Generated by Django 6.1.1 on 2026-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupCategoryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('meetup_count', models.IntegerField(default=0)),
                ('applicant_count', models.IntegerField(default=0)),
                ('average_application_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meetup_category_statistics',
                'ordering': ['-meetup_count'],
            },
        ),
    ]
